services:
 mongodb:
    image: mongo:7.0.34-jammy
    container_name: mongodb
    ports:
      - "27007:27017"

    volumes:
      - ./mongodb:/data/db


    network:
       -  backend

      restart: always

networks:
  backend:

